PATH: /Users/ASL/Desktop/Laughing_Monk/Python/WixRestaraunt/ 
rest_id: '1452613692600297'
ss_id: 1ZBLqTlCCDhjy9pXDib0pMpWqfIYNC97AzeH9LZeDTSw
headers: 
  - Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkIjoxNTg2MjEwNTUxMDE5LCJpZCI6ImNvbS53aXgiLCJkYXRhIjoiYTYzZDMyOWEtZjVjMC00M2Q4LWI1YjktMDMzZGY5MDM1ZGRiIn0.huxcKPFLKq06czNSWJdXRaBVjG8EurVQliYQNOrukLk
